//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskEpamClientApplication.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAskService", CallbackContract=typeof(AskEpamClientApplication.ServiceReference1.IAskServiceCallback))]
    public interface IAskService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAskService/Handshake", ReplyAction="http://tempuri.org/IAskService/HandshakeResponse")]
        void Handshake(string user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAskService/AskQuestion")]
        void AskQuestion(string asker, int section, string question);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAskService/ListQuestions")]
        void ListQuestions();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAskService/AddComment")]
        void AddComment(int idQuestion, string text, int idUser);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAskService/ListComments")]
        void ListComments(int idQuestion);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAskService/UpdateSkill")]
        void UpdateSkill(string user, int skill);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAskService/GetAnswerFromClient")]
        void GetAnswerFromClient(int id, string answer, string answerer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAskService/AddUser")]
        void AddUser(AskEpamEntities.EpamUser user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAskService/Autorization")]
        void Autorization(AskEpamEntities.EpamUser user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAskServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAskService/SendAnswerToClient")]
        void SendAnswerToClient(string answer, string answerer);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAskService/AskClient")]
        void AskClient(int id, string question);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAskService/SendListQuestionsToClient")]
        void SendListQuestionsToClient(AskEpamEntities.Question[] list, AskEpamEntities.QuestionSection[] sections);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAskService/SendListCommentsToClient")]
        void SendListCommentsToClient(AskEpamEntities.UserComment[] list);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IAskService/SendUserToClient")]
        void SendUserToClient(AskEpamEntities.EpamUser user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAskServiceChannel : AskEpamClientApplication.ServiceReference1.IAskService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AskServiceClient : System.ServiceModel.DuplexClientBase<AskEpamClientApplication.ServiceReference1.IAskService>, AskEpamClientApplication.ServiceReference1.IAskService {
        
        public AskServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public AskServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public AskServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AskServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public AskServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Handshake(string user) {
            base.Channel.Handshake(user);
        }
        
        public void AskQuestion(string asker, int section, string question) {
            base.Channel.AskQuestion(asker, section, question);
        }
        
        public void ListQuestions() {
            base.Channel.ListQuestions();
        }
        
        public void AddComment(int idQuestion, string text, int idUser) {
            base.Channel.AddComment(idQuestion, text, idUser);
        }
        
        public void ListComments(int idQuestion) {
            base.Channel.ListComments(idQuestion);
        }
        
        public void UpdateSkill(string user, int skill) {
            base.Channel.UpdateSkill(user, skill);
        }
        
        public void GetAnswerFromClient(int id, string answer, string answerer) {
            base.Channel.GetAnswerFromClient(id, answer, answerer);
        }
        
        public void AddUser(AskEpamEntities.EpamUser user) {
            base.Channel.AddUser(user);
        }
        
        public void Autorization(AskEpamEntities.EpamUser user) {
            base.Channel.Autorization(user);
        }
    }
}
