<?xml version="1.0" encoding="utf-8"?><Database Name="AskEpamDB" Class="AskEpamDB_LINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=EPRUSARW1092\SQLEXPRESS;Initial Catalog=AskEpamDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AskEpamDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Comments" Member="Comments">
    <Type Name="Comment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idQuestion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="dateTimeCreation" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="idUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sections" Member="Sections">
    <Type Name="Section">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserQuestions" Member="UserQuestions">
    <Type Name="UserQuestion">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Question" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="idSection" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="password" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Function Name="dbo.ADD_USER" Method="ADD_USER">
    <Parameter Name="Login" Parameter="login" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Pwd" Parameter="pwd" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="ADD_USERResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.[AUTHORIZATION]" Method="AUTHORIZATION">
    <Parameter Name="Login" Parameter="login" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Pwd" Parameter="pwd" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="AUTHORIZATIONResult">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="login" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="skill" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GET_USER_BY_ID" Method="GET_USER_BY_ID">
    <Parameter Name="id_user" Type="System.Int32" DbType="Int" />
    <ElementType Name="GET_USER_BY_IDResult">
      <Column Name="login" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="skill" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.COMMENTS_LIST" Method="COMMENTS_LIST">
    <Parameter Name="idQuestion" Type="System.Int32" DbType="Int" />
    <ElementType Name="COMMENTS_LISTResult">
      <Column Name="text" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="dateTimeCreation" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="login" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>