<?xml version="1.0" encoding="utf-8"?><Database Name="AskEpamDB" Class="AskEpamDB_LINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=EPRUSARW1092\SQLEXPRESS;Initial Catalog=AskEpamDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AskEpamDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserQuestions" Member="UserQuestions">
    <Type Name="UserQuestion">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Question" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>